### PR TITLE
Update to Log4J 2 #106

### PR DESCRIPTION
**Pull request by ttben**
Basically replace log4 v1 with v2, more efficient and with less memory overhead
I think it would be interesting to rerun PR 105.
WDYT?

### CODE REVIEW

**Comment by davisjam** [comment]
I would be surprised if changing log4 versions affected the results of #105, which I believe are more strongly influenced by loading a Git repository into memory. The memory usage amplitude might decrease but probably not appreciably.

**Comment by davisjam** [comment]
@ttben Does this PR have any backwards compatibility implications for existing projects that use RepoDriller?

**Comment by ttben** [comment]
Git repositories definitely weight more than log4j but logging performance can have a huge impact nevertheless IMO.

Since log4j2 is embedded in RepoDriller, I think they will have to rename `log4j.xml` to `log4j2.xml`. And I think that's it.

**Comment by mauricioaniche** [comment]
We forgot to change the `log4j.xml` to `log4j2.xml` in the src/test folder. Just did it directly to the master branch.

**Pull request merged**
