### PR TITLE
Collect configuration

### PR DESCRIPTION
**Pull request by mauricioaniche**
This PR attempts to provide RepoDriller with the possibility of configuring what to extract from the repository. Hopefully, this will speed up studies that do not require parts of the commit (such as diffs, source code, etc)

Related issue: #41

### CODE REVIEW

**Comment by mauricioaniche** [comment]
Performance stats of your PR:

When collecting everything:
Min memory used    : 30.35 MB
Max memory used    : 515.63 MB
Median free memory : 183.80 MB
Commits per second : 1.58

When collecting nothing:
Min memory used    : 105.48 MB
Max memory used    : 672.01 MB
Median free memory : 351.18 MB
Commits per second : 39.85

**Comment by mauricioaniche** [comment]
Performance stats of your PR:

When collecting everything:
Min memory used    : 73.31 MB
Max memory used    : 550.56 MB
Median free memory : 263.73 MB
Commits per second : 1.28

When collecting nothing:
Min memory used    : 96.71 MB
Max memory used    : 659.29 MB
Median free memory : 346.42 MB
Commits per second : 37.54

**Comment by mauricioaniche** [comment]
@davisjam @ayaankazerouni I just implemented a simple `collect()` method where users can define which data to extract from the repository. As you can see in the automatic comment above, the difference between collecting everything and collecting nothing is > 35 commits per second! So, indeed it makes a lot of sense for the user to configure what she really needs to be extracted from our framework!!

In terms of memory, this data is still quite misleading. It's really hard to understand exactly what we are spending. I just spend an hour debugging the memory usage on IntelliJ, and it seems that JGit is quite expensive, due to the number of Strings it generates behind the scenes. Thanks, GC, for being so awesome. In the future, avoiding JGit might be a nice option if we plan to save memory. 

Can someone just give this PR a quick check, so that I can merge? Tests are passing!

**Comment by mauricioaniche** [comment]
Performance stats of your PR:

When collecting everything:
Min memory used    : 74.74 MB
Max memory used    : 551.49 MB
Median free memory : 210.46 MB
Commits per second : 1.40

When collecting nothing:
Min memory used    : 27.50 MB
Max memory used    : 591.98 MB
Median free memory : 272.89 MB
Commits per second : 37.21

**Comment by mauricioaniche** [comment]
Performance stats of your PR:

When collecting everything:
Min memory used    : 32.68 MB
Max memory used    : 612.13 MB
Median free memory : 304.59 MB
Commits per second : 40.63

When collecting nothing:
Min memory used    : 30.56 MB
Max memory used    : 594.50 MB
Median free memory : 310.96 MB
Commits per second : 47.32

**Comment by mauricioaniche** [comment]
Performance stats of your PR:

When collecting everything:
Min memory used    : 66.47 MB
Max memory used    : 553.98 MB
Median free memory : 209.25 MB
Commits per second : 1.23

When collecting nothing:
Min memory used    : 44.13 MB
Max memory used    : 609.56 MB
Median free memory : 290.09 MB
Commits per second : 37.98

**Comment by mauricioaniche** [comment]
Performance stats of your PR:

When collecting everything:
Min memory used    : 59.43 MB
Max memory used    : 566.35 MB
Median free memory : 297.63 MB
Commits per second : 1.50

When collecting nothing:
Min memory used    : 29.66 MB
Max memory used    : 592.49 MB
Median free memory : 296.81 MB
Commits per second : 38.97

**Comment by mauricioaniche** [comment]
Performance stats of your PR:

When collecting everything:
Min memory used    : 75.50 MB
Max memory used    : 557.57 MB
Median free memory : 215.46 MB
Commits per second : 1.53

When collecting nothing:
Min memory used    : 26.67 MB
Max memory used    : 606.77 MB
Median free memory : 275.35 MB
Commits per second : 40.22

**Comment by ayaankazerouni** [comment]
> @davisjam @ayaankazerouni ... Can someone just give this PR a quick check, so that I can merge? Tests are passing!

Sorry, @mauricioaniche, I didn't see this PR until now!

**Pull request merged**
